### ISSUE TITLE
The config files does not exit.

### ISSUE THREAD

**Issue by Zhangxx1218** [InhwanBae/SingularTrajectory#4]
When I run the scripts example that you supported,I have met an issue: config json does not exit.Can you support right configs?Thank you very much!

**Comment by InhwanBae** [comment]
Hi @Zhangxx1218,

Thank you for your interest in my work! The error you're encountering is likely due to a missing config file or an incorrect path. Are you still facing the issue even after downloading the pre-trained model? You can download it from [this link](https://github.com/InhwanBae/SingularTrajectory/releases/tag/v1.0)!

**Comment by InhwanBae** [comment]
I'm closing this issue for now. Feel free to open another issue if you have any further questions!
